### ISSUE TITLE
Syntax highlighting in docs is not accessible 

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#1027]
- What RMWC Version are you using [major.minor.patch]:

- Name your build system [Webpack, Rollup...]:

- Describe the bug with as much detail as possible:

- What happened, and what was supposed to happen:
![image](https://github.com/rmwc/rmwc/assets/1300390/2a751dec-a2f1-454f-bbe0-4acd152b900c)

**Comment by jensborch** [comment]
This should be solved by https://github.com/rmwc/rmwc/pull/1233
