### ISSUE TITLE
Syntax error in Data Tables "Scrollable / Sticky Rows and Columns" & "Form Controls"

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#1029]
- What RMWC Version are you using [major.minor.patch]:

- Name your build system [Webpack, Rollup...]:

- Describe the bug with as much detail as possible:

- What happened, and what was supposed to happen:
![image](https://github.com/rmwc/rmwc/assets/1300390/918d6425-cbaf-4bac-9ac6-51cb973fd06e)

**Comment by EmiBemi** [comment]
Okay the fix is just removing type `FormEvent<>` from the `evt` in the readme.tsx files.

**Comment by b-d-m-p** [comment]
Solved by https://github.com/rmwc/rmwc/pull/1038. Closing.
