### ISSUE TITLE
Select Menus > Controlled / Uncontrolled missing

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#1033]
- What RMWC Version are you using [major.minor.patch]:

- Name your build system [Webpack, Rollup...]:

- Describe the bug with as much detail as possible:

- What happened, and what was supposed to happen:

![image](https://github.com/rmwc/rmwc/assets/1300390/af6b39c4-a0b6-4718-a983-fd021863302e)

**Comment by EmiBemi** [comment]
Was fixed on https://github.com/rmwc/rmwc/pull/1020
