### ISSUE TITLE
Text Fields > HTML Input Types: Range slider line missing

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#1035]
- What RMWC Version are you using [major.minor.patch]:

- Name your build system [Webpack, Rollup...]:

- Describe the bug with as much detail as possible:

- What happened, and what was supposed to happen:
![image](https://github.com/rmwc/rmwc/assets/1300390/3b40300e-01e7-4a90-8e81-3637f34d900b)

**Comment by EmiBemi** [comment]
This issue also exists on v 8

**Comment by b-d-m-p** [comment]
I'll look into it.

**Comment by b-d-m-p** [comment]
Fixed in https://github.com/rmwc/rmwc/pull/1051
