### ISSUE TITLE
Portal Page broken (https://rmwc.io/version/8.0.8/ || https://rmwc.io/portal)

### ISSUE THREAD

**Issue by kale1d0code** [rmwc/rmwc#1145]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?
RMWC website

- Describe the bug with as much detail as possible:
navigating to portal page for version 8.0.8 causes white screen.
navigation on current version (14.0.3-alpha.0) shows provider page.

- What happened, and what was supposed to happen:
portal page to be displayed

**Comment by jensborch** [comment]
Thanks for reporting this. The documentation site is somewhat broken right now (see issue #1180). We will look into fixing your issue together with issue #1180

**Comment by EmiBemi** [comment]
Fixed in https://github.com/rmwc/rmwc/pull/1185
