### ISSUE TITLE
typescript error importing any rmwc packages when using modern moduleResolution configs

### ISSUE THREAD

**Issue by radix** [rmwc/rmwc#1166]
- What RMWC Version are you using [major.minor.patch]: ^14.0.2-alpha.7
- Name your build system [Webpack, Rollup...]: vite
- typescript version: 5.2.2
- npm version: 10.2.3

- Describe the bug with as much detail as possible:

I've installed with `npm install @rmwc/slider@14.0.2-alpha.7`, but when I try to import it...

- What happened, and what was supposed to happen:

I get this error:

```
src/Scene.tsx:23:25 - error TS7016: Could not find a declaration file for module '@rmwc/slider'. 'C:/Users/radix/Projects/arpeggiorpg/ui/node_modules/@rmwc/slider/index.mjs' implicitly has an 'any' type.
  There are types at 'C:/Users/radix/Projects/arpeggiorpg/ui/node_modules/@rmwc/slider/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@rmwc/slider' library may need to update its package.json or typings.

23 import { Slider  } from '@rmwc/slider';
                           ~~~~~~~~~~~~~~
```

I tried the same with `@rmwc/button` and got the same error.

**Comment by EmiBemi** [comment]
Hmm, I'm not able to reproduce this error. Is it possible that you could create a code sandbox perhaps?

**Comment by EmiBemi** [comment]
I'm a bit interested if you experience the same if you also install the "rmwc" package as a whole? `"rmwc": "14.0.2-alpha.7",`

**Comment by jensborch** [comment]
@radix We have just released version 14, could you check if the problem still persists?

**Comment by radix** [comment]
@jensborch same error in the new release.

Doesn't the error message indicate the problem accurately? Is there a problem with the `exports` declaration in the rmwc package.json files?

@EmiBemi the same happens when I try `import { Slider } from 'rmwc'` after installing rmwc 14.0.0

**Comment by radix** [comment]
I have been able to get the types to import by modifying the package.json files so that there is a "types" entry inside of the "exports" objects. e.g., in @rmwc/slider's package.json:

`  "exports": {
    ".": {
      "import": "./index.mjs",
      "types": "./index.d.ts",
      "require": "./index.js"
    },
    "./styles": {
      "import": "./styles.mjs",
      "require": "./styles.js"
    }
  },
`

and likewise in rmwc's package.json.

**Comment by radix** [comment]
I'm not sure why y'all wouldn't be getting this error too, but maybe it has something to do with my compilerOptions:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable", "ES2023.Array"],
    "module": "ESNext",
    "skipLibCheck": true,

    "strict": true,
    "noUncheckedIndexedAccess": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "types": ["vite/client"]
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
  ],
  "exclude": [
    "node_modules"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

**Comment by jensborch** [comment]
Have you tried the new (non alpha) version 14.

We have the following (working) configuration in one of our projects using this version: 

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "lib": ["es2020", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "rootDir": ".",
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "target": "es2015"
  },
  "exclude": ["node_modules", "tmp"]
}
```

With the version 14 release we have migrated to Vite, your error might be caused by this. Right now our priority is to look into some of our other errors, like the broken documentation site, but we will try to help as soon as possible.

**Comment by radix** [comment]
@jensborch yes, the released version 14 also gives the same error. This is what I meant by "same error in the new release", sorry I wasn't more specific.

I narrowed down the compiler option that seems to be breaking it - it's about [moduleResolution](https://www.typescriptlang.org/tsconfig#moduleResolution).

It seems that the imports work when set to `Node` or `Node10`, but when set to `NodeNext`, `Node16`, or `bundler`, they fail in the way I have mentioned above.

So anyway... I guess the fix is to just put "types" in the export declarations in package.json.

**Comment by jensborch** [comment]
@radix Version 14.0.1 has been release with updated package.json files
