### ISSUE TITLE
AddSass compiler

### ISSUE THREAD

**Issue by jensborch** [rmwc/rmwc#1183]
At some point during our upgrade to Google Material version 14 the Sass compiler became a required dependency for RMWC to work. This dependency should not be need, we should try to remove it or add it as a peer dependency.

**Comment by b-d-m-p** [comment]
@jensborch @EmiBemi I addd sass, but the chips, which require it, don't seem to have any issues without it.

**Comment by b-d-m-p** [comment]
Team decision: merge this.

**Comment by b-d-m-p** [comment]
Jens added it as a dependency when NX demanded it, so we don't need to merge this. Closing.
