### ISSUE TITLE
Weirdly incorrect relative imports in .d.ts files

### ISSUE THREAD

**Issue by radix** [rmwc/rmwc#1201]
I'm having trouble getting typechecking on my usage of RMWC now that #1166 is fixed. I can import components and even use them with no typescript errors, *but* the props of RMWC components are clearly not being typechecked (if I pass random garbage props, the type checker does not complain).

While trying to figure out what's going on, I noticed that there are some bad imports in the '.d.ts' files shipped in the rmwc distributions. e.g.,

```
/Users/radix/Projects/arpeggiorpg/ui/node_modules/@rmwc/avatar/lib$ head -1 index.d.ts
import * as RMWC from '../../../types/src/index.ts';
```

Notice that the three "../../.." segments would land inside the "node_modules" which would lead to looking for "types" as a top-level package, which obviously won't work. Granted, my editor and my typescript checker are not complaining about this, but if I try to "go to definition" on that RMWC import my editor can't find the file, so I suspect this has something to do with my lack of typechecking, but I'm not totally sure.

So, can anyone confirm whether this confusing "../../.." import is actually valid? It seems to me it should actually be doing an absolute import of "@rmwc/types" instead of a relative import into a different package.

**Comment by jensborch** [comment]
I am guessing this is an issue with how we are configuring [vite-plugin-dts](https://github.com/qmhc/vite-plugin-dts), but I can't figure out where the error is :-(

**Comment by radix** [comment]
Just as an added data-point: when I manually hacked my copy of the .d.ts file to just import from `@rmwc/types`, my typescript finally came to life and started giving me actual prop type checking on the RMWC components, so this bad import does seem to be the source of my lack of typechecking.

**Comment by radix** [comment]
@jensborch thank you! that seems to be the last problem I had with RMWC. Everything is working now.
