### ISSUE TITLE
Uncontrolled `TextField` in version 14+ does not work correctly with `react-hook-form`

### ISSUE THREAD

**Issue by ciepol** [rmwc/rmwc#1255]
Sample code: https://codesandbox.io/p/sandbox/rmwc-forms-pyw244?file=%2Fsrc%2FApp.tsx

You can observe in the code sandbox above that input from `TextField` is not preserved. (1st example)
Switching to controlled version by using `react-hook-form`s `<Controller>` works correctly (3rd example)

It works correctly when switching back `@rmwc/textfield` to version `8.0.8`.

It works fine without `react-hook-form`: https://codesandbox.io/p/sandbox/uncontrolled-text-field-lrnn98?file=%2Fsrc%2FApp.tsx

**Comment by b-d-m-p** [comment]
Fixed by @EmiBemi

**Comment by b-d-m-p** [comment]
Fixed in 14.0.9
