### ISSUE TITLE
Bug Crunch January '24

### ISSUE THREAD

**Issue by EmiBemi** [rmwc/rmwc#1284]
- [x] Switch styling (keeps rmwc default theme unless `@rmwc/theme/styles` is imported)
- [x] Switch onClick/onChange
- [x] Switch evt.currentTarget.checked does not work
- [ ] Switch stays focused after interaction
- [x] Select (enhanced) gets unwanted padding from wrapping anchor
- [x] Select (native) can't be fullwidth (maybe due to new rmwc-default-width class added)
- [x] RMWC incompatible with react-hook-form

**Comment by jensborch** [comment]
I'll jump on React Hook Form
