### ISSUE TITLE
IconButton onClick fires twice

### ISSUE THREAD

**Issue by joao678** [rmwc/rmwc#1299]
- What RMWC Version are you using [major.minor.patch]: 14.0.7

- Name your build system [Webpack, Rollup...]: Vite

- Describe the bug with as much detail as possible: When I click an IconButton the click event is fired two times as seen here, [https://codesandbox.io/p/devbox/gallant-keldysh-6wrkyl](https://codesandbox.io/p/devbox/gallant-keldysh-6wrkyl)
Check the chrome devtools using F12 for the console.log (not the integrated codesandbox "Preview Console" button as this dosen't happen there although the same thing happens in the regular browser)

- What happened, and what was supposed to happen: After some investigation, I came to the conclusion that there's an event attached to both the `<button>` and  `<i>` tags and they're both fired at the same time, is the extra event on the `<i>` intended?

**Comment by b-d-m-p** [comment]
Thanks for creating the issue. We will look into it. Do you know if you're running strict mode? We have an issue that causes things to fire twice. https://github.com/rmwc/rmwc/issues/815
