### ISSUE TITLE
Select defaultValue is not working when enhanced={{renderToPortal: true}} is set

### ISSUE THREAD

**Issue by przystuj** [rmwc/rmwc#1395]
- What RMWC Version are you using [major.minor.patch]: 14.2.1

- Name your build system [Webpack, Rollup...]: pnpm with vite

- Describe the bug with as much detail as possible:

when I add select like this:
` <Select
            defaultValue={'Cookies'}
            enhanced={{ renderToPortal: true }}
            label="renderToPortal"
            options={['Cookies', 'Pizza', 'Icecream']}
          />`
the default value is not displayed

this displays defaultValue properly:
`<Select
            defaultValue={'Cookies'}
            enhanced
            label="enhanced"
            options={['Cookies', 'Pizza', 'Icecream']}
          />`

![image](https://github.com/rmwc/rmwc/assets/25057392/c4ba6616-e52d-4082-bafc-5d7870541b6a)

**Comment by EmiBemi** [comment]
After some investigation I've found that the problem is caused by the menu being rendered to a portal. More specifically the error was introduced in https://github.com/rmwc/rmwc/pull/850/files#diff-4bdf91d85ceb1e7908ff7d09a600ac02ee8287f48b7e79063155fc836ed93e27.

I will look into a solution.

**Comment by EmiBemi** [comment]
PR openened (https://github.com/rmwc/rmwc/pull/1428)
