### ISSUE TITLE
Add more customization to TextField

### ISSUE THREAD

**Issue by yodchahan** [rmwc/rmwc#1435]
## RMWC 
- What RMWC Version are you using [major.minor.patch]: 14.2.2

I want to have a currency abbreviation (USD, EUR and so on) inside the TextField on the right side. In the current example there is "DKK" as currency and it should be just a text (not a button, it should have a default pointer and should not have tab-index: "0").
![template (1)](https://github.com/rmwc/rmwc/assets/161447031/56f86d1d-10fb-4994-a1b8-93994e4b07e2)

The current library version allows me to only add icon on the left, or icon-button on the right.

![template](https://github.com/rmwc/rmwc/assets/161447031/b68f4f99-46ba-4cbe-8807-0fa4f34a02d8)

MUI lib is more cutomizible at this point. We can add whatever we want to where we want without creating unnesessary buttons and additional wrapping into the `<i>` tag
https://mui.com/material-ui/react-text-field/

**Comment by EmiBemi** [comment]
Hi! Have you tried the suffix/prefix prop on TextField? Let me know if this is sufficient.

**Comment by yodchahan** [comment]
Hi, @EmiBemi, I've tried in the documentation example it doesn't work as expected there and in my project the same thing.
![image](https://github.com/rmwc/rmwc/assets/161447031/062c6cd6-e13c-4a69-a7c8-c2fc493c3ec2)

**Comment by yodchahan** [comment]
Hi, Emilie, it doesnt work from the box. It renders the prefix in the DOM but it is invisible
[image]

**Comment by EmiBemi** [comment]
It should become visible once the textfield is activated/focused. From what I can tell it works as inteded as per documented at https://m2.material.io/components/text-fields#filled-text-field if you scroll to the section "Filled text fields with prefix text"
