### ISSUE TITLE
TextField (date) doesn't show cursor as "pointer" when hovers the calendar icon

### ISSUE THREAD

**Issue by yodchahan** [rmwc/rmwc#1573]
RMWC v14.3.4

**Description:**
- Go to https://rmwc.io/text-fields
- scroll to "HTML Input Types"
- find a date field and hover the mouse over the calendar icon
<img width="155" alt="image" src="https://github.com/user-attachments/assets/b53ed99a-2981-4b52-899a-0339632438f5">

Actual: the cursor is "arrow" which doesnt indicate that this is a clickable element
![image](https://github.com/user-attachments/assets/f662b900-fc0c-4848-ae71-e1cf060634f9)
Expected: the icon should be "pointer"
![image](https://github.com/user-attachments/assets/85cb2d77-8f25-442c-ae6d-e6f92993308f)

P.S. the bug is not only about date field, but any field that has an action in the field, like this field with color choosing:
![image](https://github.com/user-attachments/assets/898d9dae-8937-4431-b933-34f4bef2f02d)

**Comment by EmiBemi** [comment]
This is not exposed by the mdc API nor is this how the native date picker works, so I believe this is expected. If it's needed I would style it locally.
