### ISSUE TITLE
Text field label not adjusting to state change

### ISSUE THREAD

**Issue by suenwl** [rmwc/rmwc#338]
### What RMWC Version are you using?
3.0.4

### What build system are you using?
Create React App, we're using flow as well

### What are the steps to reproduce the bug?
When text is added via a state change to a text field which does not originally have any value, the label of the textfield does not automatically adjust to accommodate the text

### What is the expected behavior?
The label should shift/shrink to the top of the text field 

### What is the actual behavior?
Currently, the label remains in its original location until the text field is put in focus by clicking on it
<img width="217" alt="screen shot 2018-10-08 at 17 28 17" src="https://user-images.githubusercontent.com/20860311/46614904-a526ac80-cb1f-11e8-9baa-f5b36e8c1527.png">

**Comment by jamesmfriedman** [comment]
Fixed in 3.0.5. Sorry for the delay on this one.

**Comment by suenwl** [comment]
Thank you!
