### ISSUE TITLE
Feature Request/Question: how to disable focus after click ?

### ISSUE THREAD

**Issue by casperan** [rmwc/rmwc#484]
Issue
- experienced: focus stays active after click/tap
- expected: focus disappears after click/tap

example cases

1. https://material.io/develop/web

a. click on the "Components" collapsibleList like list item in the left drawer
  - see that it fires the ripple effect
  - see that the ripple background disappear after
  - see that it unfolds
  - see that it doesn't show background colour after
  - see that it doesn't show the active url
  = GOOD

b. click on the "Animation" list item
  - see that it fires the ripple effect
  - see that the ripple background disappear after
  - see that the selected style indicator is present
  - see that it doesn't show background colour after
  - see that it doesn't show the active url
  = GOOD
    - except for the way they handle the page reload with a flicker, but that's another issue

2. https://rmwc.io & implementations

a. click on the "Getting Started" collapsibleList list item in the left drawer
  - see that the ripple background does not disappear after = ???
    - until clicking/tapping outside

b. click on the "Installation" list item
  - see that the ripple background does not disappear after = ???
    - until clicking/tapping elsewhere
  - see that the url location appears in the bottom left corner of the viewport = ???
    - until click/tapping elsewhere
  = ???

NOTES
- I understand the current behaviour can have benefits for accessibility and keyboard aficionados, but otherwise it just feels like a distraction, and there are other ways to care for accessibility and keyboard control, as the implementation on material.io, google apps/websites, shows, so I can't imagine this is an optimal behaviour.
- When researching this issue I came many other threads in different projects where people stumble over this too.
- material.io is not experiencing this on 

QUESTION
1. first, how can we get the same behaviour as on material.io and in a way that feels natural and intuitive ?
- not just switching from an anchor or other focusable element to another with an onClick handler and manually implement tabIndex
- I still want to support accessibility and keyboard control and use NavLink a anchor tags from react router

THOUGHTS
- collapsible using span tag instead of an a anchor tag since I read somewhere it is should not be focusable, but that doesn't work, and feels like a hack.
- using onClick handlers instead of NavLink a anchor tags in list items
- setFocus in another component using useEffect after click when the action loads something else and that is rendered in a spa or universal that is not reloading from server with the reload flash/flicker. (on material.io it may happen because of a http request to reload the page from server), and also feels like a hack.
- trying to catch and override the .mdc-ripple-upgraded--background-focused or other relevant...
- try to annihilate the focus background with sass but it will probably still show the url of the focused
- applying an eventListener to combat any eventListener that mdc foundation potentially applies to do this...
- the <tab> key should enable focus, <esc> exit/disable focus as were it a dialog.. of course that needs to be considered when there are actual dialogs. arrow and space keys should be scroll by default. (although it could use some investigation, as if there's a possible balance with the arrow keys in context with lists, trees, selects, and similar, it would be relevant). Ideally I would want an entire <tab> key activated menu with keyboard control settings which can be set when first triggered in an app.
- thoughts shared in the discord channel.
- ...these are just thoughts... but what to do ? How can we get the focus for those who need it when relevant, and have it be latent when not needed/wanted ?

Follow Up
- it's related to tabIndex
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
- btw check the behaviour above, it also only show indicator when using <tab> not on eg. mouse click. see on the collapsible too.
- I wonder how it's possible to control the eventListener action that's fired when clicking/tapping/pressing an element like an IconButton, ListItem, and the likes... to tell it not to add the style on focus unless it's a keyboard <tab> that sets it focused.

**Comment by casperan** [comment]
applying: onClick={() => document.activeElement.blur()}
as prop to each list item helps, but there are better ways of handling this
- component scoped event listener
- document scoped event listener
- upstream in either mdc-components-web or rmwc

but this needs more investigation
what's the reason mdc and rmwc did it this way ?
what were the trade offs ?

intuitive and smooth accessibility and keyboard control should be preserved
both <tabs> and <arrow> keys must work
<escape> must unset focus while in <tab>'ed keyboard mode, giving back focus to the container and scroller
<space> must select in some cases
<enter/return> must click in some cases

relevant code
- rmwc/src/list/collapsible-list.tsx handleKeyDown(...)
- rmwc/src/list/list.tsx handleKeyDown may inherit behaviour from MDCListFoundation etc
- ...lots of edge cases, and inter relations, no wonder it's complicated ;)

**Comment by jamesmfriedman** [comment]
Yeah, I read this a while ago. I think I started responding on my phone and got distracted.

This is a complicated issue. Just to parse out what you're saying a bit more, the implementation on RMWC does NOT match the ones on Material.io? I just want to make sure I understand before trying to think through as to why.

**Comment by emalsidog** [comment]
Are there some new ways to solve this issue? This behaviour is really strange. It would be handy to have some flag like "removeFocusAfterAction"

**Comment by EmiBemi** [comment]
@emalsidog None that I know of currently. I will reopen this issue

**Comment by emalsidog** [comment]
I came up with solution yesterday. I added a global click event listener at the top of my components. Then I am just listening to events and checking for the className of a clicked element. If the clicked element is a RMWC component, I call the blur function.

`React.useEffect(() => {
    const handleBlur = (e) => {
      e.target.blur();
      e.target.parentNode.blur();
    };

    window.addEventListener('click', (e) => {
      console.log(e);

      // Code to remove focus from element after clicking

      // Buttons
      if (e.target.className === 'mdc-button__ripple') {
        handleBlur(e);
      }

      // Selects, Collapsibles
      if (e.target.className.includes('mdc-list-item')) {
        handleBlur(e);
      }

      // Case if other element inside collapsible header was clicked
      const possibleClassNamesOfElementsInsideCollapsible = [
        'mdc-typography--body1',
        'mdc-typography--headline6',
        'rmwc-icon',
      ];

      const foundClassName = possibleClassNamesOfElementsInsideCollapsible.find(
        (className) => e.target.className.includes(className),
      );

      if (foundClassName) {
        // try to find collapsible in upper elements

        if (
          foundClassName === 'mdc-typography--body1'
            && e.target.parentElement.className.includes('mdc-list-item')
        ) {
          e.target.parentElement.blur();
          return;
        }

        const upperElement = e.target.parentElement.parentElement;

        if (upperElement.className.includes('mdc-list-item')) {
          upperElement.blur();
        }
      }

      // Checkboxes
      if (e.target.className === 'mdc-checkbox__native-control') {
        handleBlur(e);
      }

      // Icon buttons
      if (e.target.className.includes('mdc-icon-button')) {
        handleBlur(e);
      }

      // Radio buttons
      if (e.target.className === 'mdc-radio__native-control') {
        handleBlur(e);
      }

      // Switches
      if (e.target.className === 'mdc-switch__native-control') {
        handleBlur(e);
      }
    });
  }, []);`
