### ISSUE TITLE
List HandleSelection

### ISSUE THREAD

**Issue by lbell** [rmwc/rmwc#554]
Converting over from the defunct Material-Components-Web-React which has a [`singleSelection`](https://github.com/material-components/material-components-web-react/tree/master/packages/list#single-selection) property on Lists making it easy to pass the selected index of a list back up my app with the `handleSelect` wizardry.

Anything similar in RMWC or do I have to hard code an `onClick` for each list item?

**Comment by jamesmfriedman** [comment]
right now, onClick for reach item, but this seems like a useful update to get an index back.

**Comment by jensborch** [comment]
Fixed by https://github.com/rmwc/rmwc/pull/1220
