### ISSUE TITLE
Portal doesn't support SSR

### ISSUE THREAD

**Issue by p-98** [rmwc/rmwc#708]
- What RMWC Version are you using:
6.1.4

- Name your build system [Webpack, Rollup...]:
next.js, but should occur whenever SSR is used

- Describe the bug with as much detail as possible:
RMWC Portal throws an error on compilation when serverside rendering is used:
`ReferenceError: document is not defined`

This is due to the ref in the Portal component being initialized with `document.createElement('div')`. 

I was wondering because I don't know what this ref is being used for and replaced the `<Portal/>` with `<div id="rmwcPortal"/>`. In my usecase This solved the problem and it works with SSR.

**Comment by weiserhase** [comment]
I think you used too much Typenscript i gues

**Comment by sakekasi** [comment]
Just wanted to bump this. I'm using `Portal` in SSR, and it still has this issue

**Comment by EmiBemi** [comment]
Reopened due to this still being an issue
