### ISSUE TITLE
rmwc.io bugfixes

### ISSUE THREAD

**Issue by EmiBemi** [rmwc/rmwc#802]
After release of RMWC v8, a few bugs on rmwc.io has appeared. Here's a list:
- [x] 1. Textfield datepicker is gone
- [ ] 2. Theme fab menu is broken when you scroll
- [ ] 3. When clicking on the "Menus" component docs, a menu appears in the top left corner https://github.com/jamesmfriedman/rmwc/issues/800
- [x] 4. Select displays the value and not the label when using the `{value: '1', label: 'cookies'}` structure. PR that fixes this issue: https://github.com/jamesmfriedman/rmwc/pull/801
- [x] 5. Menu anchoring seems to be aligning to the right of the select not the button

**Comment by b-d-m-p** [comment]
4 is related to the renderToPortal prop. If you uncheck the "Render to portal" checkbox, it will appear clipped over thje button in the div above and if you  check the box, it will appear that it does not work, but it is not anchored to the proper place and appears at the top. If you uncheck it and scroll up, you can see it is not there anymore.

**Comment by b-d-m-p** [comment]
> 1. Textfield datepicker is gone

@EmiBemi You're talking about the native Chrome datepicker, yeah?
The date picker appears in Firefox Developer Edition, not in Chrome though.

**Comment by b-d-m-p** [comment]
> 2. Theme fab menu is broken when you scroll
What is the fab here? Like Floating Action Button? The theme switcher menu is appearing in the top left. Is this the issue you are talking about? This is the same renderToPortal problem as no. 3.

**Comment by EmiBemi** [comment]
@b-d-m-p 
1: Yes it's broken in Chrome and Edge that uses chromium
2: Yes the theme picker in the top left
3: This is what I mean: 
<img width="548" alt="Screenshot 2022-06-17 at 16 34 02" src="https://user-images.githubusercontent.com/12230809/174319507-0c5f47b3-b916-46a4-85ac-a05dedbb8521.png">

**Comment by b-d-m-p** [comment]
3. is this bug https://github.com/jamesmfriedman/rmwc/issues/800 I'm looking at the portal code, but haven't figured out how to approach it yet.

**Comment by EmiBemi** [comment]
Remaining bugs are issued in https://github.com/rmwc/rmwc/issues/800
