### ISSUE TITLE
Disabled MenuItems are expected to not be interactable

### ISSUE THREAD

**Issue by kintz09** [rmwc/rmwc#847]
[Original Message from Discord](https://discord.com/channels/490680848979591168/490680848979591172/1063224485370671145)

### Affected Versions
I believe all versions are likely affected, but I verified the following versions:

- 8.0.3
- 7.0.3
- 5.7.2

### Bug Overview
Issues identified with a disabled MenuItem:

1. Clicking the disabled menu item triggers the onSelect event to fire
2. Keyboard navigation treats the disabled menu item as enabled and allows interaction
3. Text color is not set to the expected disabled color

### Recreate Issue
Paste the following code into the Code to recreate issue in RMWC documentation for the version you want to test.

```jsx
function Example() {
  const [open, setOpen] = React.useState(false);

  return (
    <MenuSurfaceAnchor>
      <Menu
        open={open}
        onSelect={(evt) => console.log(evt.detail.index)}
        onClose={(evt) => setOpen(false)}
      >
        <MenuItem>Item One</MenuItem>
        <MenuItem disabled>Item Two (disabled)</MenuItem>
        <MenuItem>Item Three</MenuItem>
      </Menu>

      <Button raised onClick={() => setOpen(!open)}>
        Menu
      </Button>
    </MenuSurfaceAnchor>
  );
}
```

1. Open the menu and click the disabled button. Observe the console output proving the onSelect callback was triggered.
2. Open the menu and use the `Down` and `Up` arrows on the keyboard to navigate through all menu items and back. Observe that while there may be no ripple on the disabled item, it still is in the focus order and becomes focused.
3. Open the menu and press the `Down` arrow on the keyboard once to focus the disabled item. Press `Enter` on the keyboard to select the menu item. Observe the console output proving the onSelect callback was triggered for the disabled menu item.
4. Open the menu and observe that the disabled menu item does not use the disabled text style.

### Other Notes
I did confirm in the Material Design guidance documentation as well as the `@material/menu` Github documentation that it was accurate to expect the disabled menu item to have a disabled appearance, have keyboard interaction disabled, and to not be selectable. 

- [Appearance of a disabled menu item in Material Design 2 documentation](https://m2.material.io/components/menus#anatomy:~:text=states%20inside%20menus-,Disabled%20actions,-Display%20actions%20as)
- [mdc-menu 8.0.0 disabled menu items](https://github.com/material-components/material-components-web/tree/v8.0.0/packages/mdc-menu#disabled-menu-items)

### Root Cause?

> This is just the ListItem component exported from the Menu module for convenience.

Since the RMWC documentation for MenuItem notes that the MenuItem component is actually the ListItem component, I took a look at the `@material/list` Github documentation to see what it notes about its disabled state.

Here's a note I found under [accessibility](https://github.com/material-components/material-components-web/tree/v8.0.0/packages/mdc-list#making-lists-accessible):
> Disabled list item will be included in the keyboard navigation.

If the MenuItem component is using the ListItem component, this could explain why the disabled MenuItem doesn't meet the Material Design guidance expectation.

**Comment by kintz09** [comment]
Has anyone been able to look into this issue yet? I'm mostly wondering if both the menu item and list item use cases can be covered by this single component or if a new component will be required. It would be amazing if we could get a proper solution in place for RMWC version 14.

**Issues:**

1. disabled menu items are included in keyboard navigation
3. user is able to select a disabled menu item using the keyboard (partial workaround available)
4. user is able to select a disabled menu item using mouse/touch input (workaround available)

I was able to put together a workaround for some of the issues this creates, but not all.

**Workarounds:**

1. I don't have a workaround for this issue. Tab index is being controlled by material and can't be overridden AFAIK
2. In your onSelect function that is called when an item is selected, check to see if it is disabled and don't fire the action if disabled. This prevents the action from firing but doesn't do anything to prevent the onSelect event in the first place, so the menu will go away on select.
3. Add the style `pointer-events: none` to the menu item if disabled to prevent interaction with mouse/touch

**Comment by EmiBemi** [comment]
Thanks for the detailed description and ideas! Fixing this now.

**Comment by kintz09** [comment]
> ```js
> function
> ```

Apologies @b-d-m-p, I just reviewed the code in my project and I misspoke when I said that was fixed with Sass. I was actually setting the `theme` prop with the appropriate text color when dynamically building the menu item.
