### ISSUE TITLE
Storybook, Vite, CRA

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#884]
- [] Get Storybook working 
- [] Can we update CRA or the fork it is using?
- [] Can we use Vite or Rollup?

**Comment by jensborch** [comment]
@b-d-m-p We have started working on migrating to Docusaurus, this means that we will not look into Vite, Rollup or Next.js. Docusaurus seems like the best option, as we can remove a lot of custom code, and get pretty much the same functionality as we have with the existing documentation site. We also plan to fixe the Storybook as a part of this. I will close this issue.

**Comment by b-d-m-p** [comment]
@jensborch can you explain why it is the best option and what advantages it has over the other approaches?

**Comment by jensborch** [comment]
@b-d-m-p Docusaurus excels at more less exactly what we want, i.e. creating documentation website. It is created by Facebook and have good traction. By using Docusaurus we can hopefully remove a lot of custom code that we have today for creating the documentation. That won't be possible with Vite etc.
