### ISSUE TITLE
Icon component's theme prop doesn't add the theme class

### ISSUE THREAD

**Issue by kintz09** [rmwc/rmwc#888]
## RMWC or MDC?
RMWC bug

This bug was replicated in version 7.0.0 - 8.0.7. This bug does not exist in version 5.7.2 or 6.1.4.

## Sandbox
https://codesandbox.io/s/rmwc-icon-theme-bug-demo-qx5cc8?file=/src/index.tsx

Alternatively, go to the Icon page in the online documentation (version 8.x) and add `theme="error"` as a prop to any of the Icon examples to replicate the bug.

## Test case
Here is a test I wrote that will fail:

```ts
it('adds mdc theme class when a valid theme prop is included', () => {
    const { queryByTestId } = render(<Icon icon="add" data-testid="icon" />);

    expect(queryByTestId("icon")).toHaveClass("mdc-theme--error")
  })
```

I read through icon/index.tsx but didn't understand how the theme prop was being handled so didn't find a fix.

**Comment by kintz09** [comment]
Update: It appears the bug was first introduced in version 7.0.0. The Icon's theme prop worked as expected in version 5.7.2 and 6.1.4.

**Comment by kintz09** [comment]
More details after reviewing git history:

- The Icon component's `theme` prop functionality is broken beginning in version 7.0.0 which was tagged on a commit from Feb 16, 2022.
- The last working version is 6.1.4 which was tagged on Sept 11, 2020.
- The last change to file /icon/index.tsx file was on Nov 26, 2020.  `25aa225e  |  Chore(Icon): Improve typing of icon render method.`

It doesn't look like that would have caused this bug, but I'm not fully understanding how the theme classes get applied in the first place.

Any thoughts on where the cause of this bug may live?

**Comment by jensborch** [comment]
@kintz09 Version 14 has been released, and we kindly request you to retest and verify whether the issue persists in the latest version
