### ISSUE TITLE
React 18 types missing RefForwardingComponent causes RMWC fail

### ISSUE THREAD

**Issue by brunozoric** [rmwc/rmwc#906]
## RMWC - React 18

- What RMWC Version are you using [major.minor.patch]: 8.0.7

- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible: 

React 18 (18.0.35) types is missing the `RefForwardingComponent`, so the RMWC types break as well.

```
(node:41755) UnhandledPromiseRejectionWarning: Error: [***] Command failed with exit code 1: yarn build --overrides {}
Deleting existing build files...
Building...
error: ../../node_modules/@rmwc/base/dist/component.d.ts(14,124): error TS2694: Namespace 'React' has no exported member 'RefForwardingComponent'.
../../node_modules/@rmwc/base/dist/component.d.ts(18,131): error TS2694: Namespace 'React' has no exported member 'RefForwardingComponent'.
```

- What happened, and what was supposed to happen:
Build broke, it should have compile the code.

Are there any undocumented workarounds that you can share?

**Comment by EmiBemi** [comment]
Here's the PR that removes the usage of `RefForwardingComponent`: https://github.com/rmwc/rmwc/pull/909

**Comment by jensborch** [comment]
@brunozoric RefForwardingComponent has been removed in version 14 so I am closing this issue
